name: CI Example

on:
  push: 
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple script
        run: echo "Hello Github Actions"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running tests.."
          python -m unittest discover
          
      - name: Build application
        run: |
          echo "building application.."
          npm install
          npm run build

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      
